### ISSUE TITLE
TypeError: this.apiClient.get is not a function

### ISSUE THREAD

**Issue by Leenus533** [bennycode/ig-trading-api#376]
my code : https://github.com/Leenus533/igbot/blob/master/index.js
i  am currently getting a type error for any class that takes the client as an input.

My code 
import "dotenv/config"
import { APIClient, MarketAPI } from "ig-trading-api"

const client = new APIClient(APIClient.URL_DEMO, process.env.IG_DEMO_API_KEY)
const market = new MarketAPI(client)

const main = async () => {
	const session = await client.rest.login.createSession(process.env.IG_DEMO_USERNAME, process.env.IG_DEMO_PASSWORD)
	console.log(session.clientId)
	const details = await market.getMarketDetails("CC.D.NG.USS.IP")
	console.log(details)
}

main()

The Terminal 

103170454 // it prints out my clientID
/home/copperr/Projects/igbot/node_modules/ig-trading-api/dist/market/MarketAPI.js:99
            const response = yield this.apiClient.get(resource);
                                                  ^

TypeError: this.apiClient.get is not a function
    at MarketAPI.<anonymous> (/home/copperr/Projects/igbot/node_modules/ig-trading-api/dist/market/MarketAPI.js:99:51)
    at Generator.next (<anonymous>)
    at /home/copperr/Projects/igbot/node_modules/ig-trading-api/dist/market/MarketAPI.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/copperr/Projects/igbot/node_modules/ig-trading-api/dist/market/MarketAPI.js:4:12)
    at MarketAPI.getMarketDetails (/home/copperr/Projects/igbot/node_modules/ig-trading-api/dist/market/MarketAPI.js:95:16)
    at main (file:///home/copperr/Projects/igbot/index.js:10:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.0.0
[nodemon] app crashed - waiting for file changes before starting...

// 

If i am using the API incorrectly please let me know.

**Comment by bennycode** [comment]
Hi @Leenus533, have you tried using this software in a TypeScript project?

**Comment by bennycode** [comment]
Closing because of inactivity.
